### ISSUE TITLE
Switch to a block structured heap

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#180]
A block structured heap will have several benefits, but the main reason to implement this now is to support linking debug info with code locations.

Borrowing from SpiderMonkey's GC I like the idea of two levels in the block structure. One large level to avoid fragmenting the virtual memory system (so that we can use bigpages). And a second level to decrease different object types from fragmenting the heap.

**Comment by PaulBone** [comment]
The hard part is done (see the gc branch, 201b55a1d9769c3b7c529202281516fcaf6b3ca6) and now I will work through the following TODO items to tidy up the branch:

- [ ] Split `pz_gc.cpp` into multiple files
- [ ] Maybe make Cell class a handle containing the pointer, lblock and index
      to avoid recalculation.
- [ ] Remove Heap::cell_bits
- [ ] Re-add poisoning.
- [ ] Implement check_heap();
- [ ] Compile some C++ stuff together or otherwise add inlining, 
      particularly for layout code.
- [ ] Update allocateLots to verify that a GC occured.
- [ ] Dump heap layout for stats.
- [ ] Avoid touching the wilderness while iterating blocks.
- [ ] Make bblock's members private.
- [ ] Move allocation of BBlocks into the BBlock class.
- [ ] Use a free list for Cells in LBlocks
- [ ] Speed up is_full and is_empty
- [ ] Use an index to speed up finding of LBlocks.
- [ ] Tune index for size classes.
-- Use stats,
-- re-tune allocateLots.p
- [ ] Avoid touching wilderness by giving bblocks a bitmap.
- [ ] Consider using C++ iterators to iterate over cells & blocks.
- [ ] Update docs in code comments
- [ ] Multiple bblocks? - file a bug, don't implement yet.

**Comment by PaulBone** [comment]
One problem I didn't anticipate and a couple other reminders of things that came up and might need refactoring.

 - [ ] Add some support for large allocations and fix the allocateLots test.
 - [ ] Rename description of free lists.
 - [ ] Check code for style.
