### ISSUE TITLE
Tidy up documentation

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#210]
There's a few style things to tidy up with documentation

 - [x] #174 Generated docs should include a copyright notice
 - [x] The developer documentation is too big and some things should be moved out / others can be put in sub lists.
 - #161 ~~Start a document for how to use the tools.~~
 - [x] #332 Document the command line options
 - [x] The Asciidoc style in the documents seems to be inconsistent, particularly WRT how the header information is set. We should pick one style and use it.
 - [x] Each document should have the link to its source on github. Many do but some don't, As above this should be done by changing how documents are processed, the explicit links in each document can be removed.
 - ~~Organised documentation into a heirachy, provide a navigation frame and breadcrumbs.~~ #341

**Comment by Gertm** [comment]
I will try to find the time to do this, but don't assign it to me just yet.

**Comment by PaulBone** [comment]
No worries, I hoped you'd be interested but also no pressure.

I also remembered that when modifying the asciidoc pipeline, there's two. One in the compiler to build the docs within that repository and one in the website's repository. Actually I don't remember, maybe it's only one script but with different templates/CSS.

**Comment by PaulBone** [comment]
@Gertm still interested?

**Comment by PaulBone** [comment]
I'm going to close this because the remaining work is in #341 and #161
