### ISSUE TITLE
Change let representation in core

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#212]
The core representation currently represents lets as:

    let v1, v2 = expr1 in
        expr2

But this can lead to code with deep nesting, unless we do something clever in the pretty-printer.  But maybe it's a better idea to improve the representation of lets allowing a sequence of lets (with or without an empty variable set, as exists now) for a sequence of code.  This will more directly represent what we want for the pretty printer, but also for other parts of the compiler.

**Comment by PaulBone** [comment]
- [x] Refactor the let representation
* ~~Don't generate tuples.~~
- [ ] Check pretty-printer output is pretty.
- [ ] Address TODO items in core.simplify.m
- [ ] Flattern out tuples during simplify..
- [ ] Add simplify pass after pre->core
- [ ] Add an assertion to check no let is constructed to bind the same variable
      twice.
- [ ] Allow anonamous binds (TODO from core.code.m)
- [ ] Allow arity-casts.

**Comment by PaulBone** [comment]
Regarding tuples and let of mutliple variables:

We'll want to flattern some tuples and keep some other tuples. It depends on how they might be treated by later stages of the compiler.  We'll probably keep those used to build argument lists and any tuples that are used in a let for several variables. but flattern others.
