### ISSUE TITLE
Un-flattern lets before codegen

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#217]
Unflatten lets. Especially where a variable has a single use during codegen so that the creation of that variable can be moved into the operands of its use. This will generate code with less stack usage.  After doing this one should

- [x] Ensure that resource usage information is properly propagated through the expression tree
- [x] Count the uses of each variable to determine which are candidates.
- [x] Delay codegen for variables that have a single use and no resource usage.
- [x] Re-enable the flattening optimisations in `core.simplify.m`
- ~~Decrease the expression stack size in `pz_generic.cpp`~~ (We need to fix #220 to do this).

**Comment by PaulBone** [comment]
I've marked this as a bug because it affects performance/memory usage in a fairly pathological way.
