### ISSUE TITLE
Project file & builder support

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#253]
Support a project file and a `plzbuild` command to build the modules and link them together correctly.

 - [x] New `plzbuild` tool
 - [x] Build in a `.build` directory, (or `build`?)
 - [x] Compiler should not have an output directory option, but an output file option.
 - [x] Source filenames in other directories
 - Path or Install issues (#305)
 - [x] Add verbose build support (pass ninja verbose flag)
 - [x] Error reporiing.
 - [x] Add ninja to dependencies in README.md     
 - [x] Read project file
 - [x] Multi-module programs
 - [x] A tool/mode to query dependencies and commands, to integrate with other build systems.
 - [x] Let ninja query dependencies per target
 - [x] Projects with more than one program/library
 - [x] multiple targets on command line
 - [x] implicit target
 - [x] Copy target to parent directory
 - [x] Add friendly names for each ninja target.
 - ~~Remove short command line switches from compiler and linker since they won't be called by hand.~~
 - [x] Add ninja to our docker images / update CI.
 - [x] Bad error messages from plzbuild
 - [x] Error checking tests in test suite

Later:

 - Write about build tool in docs. (#318)
 - Document the project file stuff. (#318)
 - If the plzbuild binary is updated then we must regenerate all ninja files. (#319)
 - Libraries (#316)
 - Let ninja infer that if we didn't update our target then other targets
    that depend on them don't need to be rebuild. (#319)
 - Project file should be (partly) generatable. eg for conditional compilation.
 - Usable from within another build system.
 - Out-of-tree builds (#320).
 - Audit / centralise how filenames for modules are discovered and created.
 - Detect if plzbuild is the installed version and therefore how to find the other tools (eg for running tests without installation). (#305)
 - The [build] commit tag is now overloaded (#321)
 - Detect import errors during dependency generation.

See also #144

**Comment by PaulBone** [comment]
Ideas:

# When building a plasma project,

Someone runs `plzbuild`:

 * `plzbuild` reads project file and understands where to find source, what source is included.
 * `plzbuild` runs `plzdep` telling it about all the source.  `plzdep` /updates/ the dependency database (`.build/depend`).
 * `plzbuild` reads the dependency database and makes a `.build/ninja.build` file.
 * `plzbuild` executes ninja, maybe copies the final target out of .build.

Also, with some extra rules ninja could know how to update the dependency database, and or even the ninja.build file?

Also, by "update" the dependency database we mean compare timestamps between files and the database to know what needs to be processed and process only those files.

# When building a Plasma program as part of something else

The programmer can write some rules for their build system to:

 * Build/update the dependency database
 * Either call plzbuild as above, or include rules/scripts to dump and import dependency information and rules to let the host build system build things.
 * It needs to support in and out of tree builds.

# When building Plasma that uses some foreign code.

I'm unsure.  using the 2nd option might be best because at the very least that shifts knowing how to invoke C compilers / linkers / build libraries onto the external build tool.

# When conditionally compiling some modules

The example came up when you have filesystem_posix.p and filesystem_win32.p and wish to include the appropriate one. The obvious way is to preprocess a source file or maybe the project file. The other end of that spectrum is including a shell command in the project file that is executed, whose output we substitute - this is slower and means extra work.  I think I like pre-processing some source first, but it does mean requiring someone to use external tools.  Pre-processing source means that we need to autodetect which source files are relevant, alternatively we pre-process the project file which lists all the source files, but that mightn't work since module names and file names might be different.

# Multiple targets

We could place all targets in the same project file. Or allow project files to say "hey, also build the project in this subdirectory".  Or both.  I prefer either the latter or both.  Either way a single Makefile / ninja.build file should be generated.

**Comment by PaulBone** [comment]
Fixed in e4e26283fd8c7bb12824d0c0bf2da49723d432cc
