### ISSUE TITLE
Build system improvments

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#302]
We can/should improve the build system in these ways:

 - [ ] Implement the Plasma driver program #144 
 - [ ] Improve how the test suite is executed, use some framework/scripts #150 
 - [ ] improve test framework output so it can work more nicely with CI #28 #226 
 - [ ] CI improvments #267 #53 #224 
 - [ ] Possibly switch build system to Ninja, maybe mason if it can work with Mercury and later Plasma. #301
