### ISSUE TITLE
Let foregin code refer to existing C symbols

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#397]
Support the following:
 - [ ] Compile time lookup with the C compiler (can find C macros).
 - [ ] AOT link time (can link with dynamic & static libraries and resolve symbols).
 - [ ] Dynamic link time (use `dlload` to find symbols).
