### ISSUE TITLE
Document some test-suite instructions for contributors

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#401]
We've got some contributor documentation.  but I don't think I've written anything about the test suite.  I need to if I expect contributors to write and update tests.  Describe:
 - [ ] How tests are executed
 - [ ] Types of tests and directories, see also #394 
 - [ ] How they're checked for correct results (expected outputs, filtering)
 - [ ] How to quickly update expected outputs when things change `./tests/update-outputs.sh`
