### ISSUE TITLE
Add continuations

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#454]
Add continuations to the AM, not to Plasma.

Depending on what's required we might want to do this in several steps.  Eg:

 - [ ] setjump/longjump style (can only jump to outer calls)
 - [ ] one shot continuations (can jump anywhere but only once)
 - [ ] normal continuations
 - [ ] delimited continuations (the beginning of a continuation is marked (I don't know if we want this at all).

Any of these but the most basic continuations need some special handling of the stack, at some point we want to add support for that.
