### ISSUE TITLE
Add some kind of code location info/debug info to PZ

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#93]
Add some kind of code location info/debug info to PZ

This will be good for debugging Plasma programs, but also tracing the interpreter.

Blocked on ~~#180~~, ~~#188~~

**Comment by PaulBone** [comment]
Here's the plan:

- [ ] Switch to a block structured heap (#180)
- [ ] Move code into it's own block type
- [ ] Code blocks can provide lookup information for code addresses. This can be used for many purposes, including debugging. I'll document the layout for this separately.
- [ ] Add context information to the PZ file format and use it to fill in the runtime.
- [ ] Allow a mode of the runtime to print this information for tracing.

**Comment by PaulBone** [comment]
Commit 1f5fa20 resolves this issue.
